# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
