# Generated by Django 5.2.1 on 2026-04-26 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_stripe_id_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_preview', models.CharField(blank=True, max_length=24)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='accounts.invitecode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_redemption', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['expires_at'], name='accounts_in_expires_16f432_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['revoked_at'], name='accounts_in_revoked_ab726e_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteredemption',
            index=models.Index(fields=['redeemed_email'], name='accounts_in_redeeme_60cdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteredemption',
            index=models.Index(fields=['redeemed_at'], name='accounts_in_redeeme_ada662_idx'),
        ),
    ]
