# Generated by Django 5.2.1 on 2026-04-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('tone', models.CharField(default='friendly', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('formula', models.TextField(help_text='LaTeX formula string')),
                ('author', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('geometry', 'Geometry'), ('algebra', 'Algebra'), ('calculus', 'Calculus'), ('physics', 'Physics'), ('complex_numbers', 'Complex Numbers'), ('topology', 'Topology'), ('statistics', 'Statistics'), ('signal_processing', 'Signal Processing'), ('fluid_dynamics', 'Fluid Dynamics'), ('electromagnetism', 'Electromagnetism'), ('thermodynamics', 'Thermodynamics'), ('quantum_mechanics', 'Quantum Mechanics'), ('information', 'Information'), ('dynamical_systems', 'Dynamical Systems'), ('finance', 'Finance')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('stage', models.CharField(default='live-demo', max_length=20)),
                ('sort_order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('objective', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(default=list)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Anonymous user identifier', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.equation')),
            ],
            options={
                'unique_together': {('user_id', 'equation')},
            },
        ),
    ]
