# Generated by Django 5.2.1 on 2026-04-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        # RENAME old user_id → anon_id FIRST (before adding user FK which creates user_id)
        migrations.RenameField(
            model_name='userprogress',
            old_name='user_id',
            new_name='anon_id',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='anon_id',
            field=models.CharField(blank=True, default='', help_text='Legacy anonymous identifier', max_length=100),
        ),
        # Now safe to add user FK (creates user_id column)
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equation_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson_step',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='variables_explored',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'equation'), name='unique_user_equation'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='equation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.equation'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
