# Generated by Django 5.2.1 on 2026-04-05 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_pro_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='equation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.equation'),
        ),
    ]
