# Generated by Django 5.2.1 on 2026-04-05 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_learningevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
