# Generated by Django 5.2.1 on 2026-04-05 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userprogress_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('anon_id', 'equation'), name='unique_anon_equation'),
        ),
    ]
