# Generated by Django 5.2.1 on 2026-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userprogress_unique_anon_equation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
