# Generated by Django 5.2.1 on 2026-04-10

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Equation = apps.get_model("courses", "Equation")
    used_slugs = set()

    for eq in Equation.objects.order_by("sort_order", "pk"):
        base_slug = slugify(eq.title) or f"equation-{eq.sort_order or eq.pk}"
        slug = base_slug
        suffix = 2

        while slug in used_slugs:
            slug = f"{base_slug}-{suffix}"
            suffix += 1

        eq.slug = slug
        used_slugs.add(slug)
        eq.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_userprogress_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation',
            name='glossary_data',
            field=models.JSONField(blank=True, default=list, help_text='Glossary term highlights'),
        ),
        migrations.AddField(
            model_name='equation',
            name='hook',
            field=models.TextField(blank=True, default='', help_text='Real-world hook shown before the lesson'),
        ),
        migrations.AddField(
            model_name='equation',
            name='hook_action',
            field=models.TextField(blank=True, default='', help_text='Action prompt shown with the visualization'),
        ),
        migrations.AddField(
            model_name='equation',
            name='lessons_data',
            field=models.JSONField(blank=True, default=list, help_text='Guided lesson steps'),
        ),
        migrations.AddField(
            model_name='equation',
            name='presets_data',
            field=models.JSONField(blank=True, default=list, help_text='Preset value configurations'),
        ),
        # Add slug without unique first so data migration can run
        migrations.AddField(
            model_name='equation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, default=''),
        ),
        migrations.AddField(
            model_name='equation',
            name='variables_data',
            field=models.JSONField(blank=True, default=list, help_text='Interactive variable definitions'),
        ),
        # Populate slugs from titles
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Now enforce uniqueness
        migrations.AlterField(
            model_name='equation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
