# Generated by Django 5.2.1 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_equation_rich_fields_and_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquationTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("locale", models.CharField(db_index=True, max_length=20)),
                ("title", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("hook", models.TextField(blank=True, default=None, null=True)),
                ("hook_action", models.TextField(blank=True, default=None, null=True)),
                ("variables_data", models.JSONField(blank=True, default=None, null=True)),
                ("presets_data", models.JSONField(blank=True, default=None, null=True)),
                ("lessons_data", models.JSONField(blank=True, default=None, null=True)),
                ("glossary_data", models.JSONField(blank=True, default=None, null=True)),
                ("equation", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="translations", to="courses.equation")),
            ],
            options={
                "ordering": ["equation__sort_order", "locale"],
                "constraints": [
                    models.UniqueConstraint(fields=("equation", "locale"), name="unique_equation_translation_locale"),
                ],
            },
        ),
    ]
