# Generated by Django 5.2.1 on 2026-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_equationtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='category',
            field=models.CharField(choices=[('geometry', 'Geometry'), ('algebra', 'Algebra'), ('calculus', 'Calculus'), ('physics', 'Physics'), ('complex_numbers', 'Complex Numbers'), ('topology', 'Topology'), ('statistics', 'Statistics'), ('signal_processing', 'Signal Processing'), ('fluid_dynamics', 'Fluid Dynamics'), ('electromagnetism', 'Electromagnetism'), ('thermodynamics', 'Thermodynamics'), ('quantum_mechanics', 'Quantum Mechanics'), ('information', 'Information'), ('dynamical_systems', 'Dynamical Systems'), ('finance', 'Finance'), ('chemistry', 'Chemistry'), ('biology', 'Biology & Genetics'), ('economics', 'Economics & Finance'), ('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('astronomy', 'Astronomy & Astrophysics'), ('linear_algebra', 'Linear Algebra')], max_length=50),
        ),
    ]
