# Generated by Django 5.2.15 on 2026-06-26 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_equation_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', '-created_at'], name='learnevent_user_created_idx'),
        ),
    ]
