/**
 * Generate frontend/src/data/whatItMeans.ts from a JSON array of authored
 * entries (the output of the "author-what-it-means" Sonnet workflow).
 *
 * Built to assemble per-equation "What does it mean?" content deterministically:
 * the agents author the prose, this script does the precise TS/escaping so the
 * file always compiles. It does NOT validate prose quality — that's the
 * whatItMeans.test.ts integrity test + a preview check.
 *
 * Usage:  node scripts/gen_what_it_means.mjs /tmp/wim_entries.json
 *   input JSON: [{ id, plainEnglish, variables:[{symbol,name,meaning,unit?}], result, interpretation }, ...]
 */
import { readFileSync, writeFileSync } from "node:fs"

const inputPath = process.argv[2] || "/tmp/wim_entries.json"
const outPath = new URL("../frontend/src/data/whatItMeans.ts", import.meta.url)

const raw = JSON.parse(readFileSync(inputPath, "utf8"))
const entries = Array.isArray(raw) ? raw : raw.entries
if (!Array.isArray(entries)) throw new Error("expected a JSON array of entries (or { entries: [...] })")

// De-dupe by id (last wins) and sort.
const byId = new Map()
for (const e of entries) {
  if (e && Number.isInteger(e.id)) byId.set(e.id, e)
}
const sorted = [...byId.values()].sort((a, b) => a.id - b.id)

const q = (s) => JSON.stringify(String(s ?? "").trim())

function renderVariable(v) {
  const parts = [`symbol: ${q(v.symbol)}`, `name: ${q(v.name)}`, `meaning: ${q(v.meaning)}`]
  if (v.unit && String(v.unit).trim()) parts.push(`unit: ${q(v.unit)}`)
  return `      { ${parts.join(", ")} },`
}

function renderEntry(e) {
  const vars = (e.variables || []).map(renderVariable).join("\n")
  return [
    `  ${e.id}: {`,
    `    plainEnglish: ${q(e.plainEnglish)},`,
    `    variables: [`,
    vars,
    `    ],`,
    `    result: ${q(e.result)},`,
    `    interpretation: ${q(e.interpretation)},`,
    `  },`,
  ].join("\n")
}

const header = `/**
 * "What does it mean?" — the plain-English decoding of each equation.
 *
 * Inspired by the 101-course lesson style: don't just show the formula, explain
 * what it is *actually saying*. Each entry gives a one-paragraph plain-English
 * reading, a symbol-by-symbol breakdown (the "decode the variables" table), what
 * the result represents, and the intuition / "so what".
 *
 * Pure data + a typed accessor — trivially unit-testable, no runtime deps. The
 * \`LearnMorePanel\` renders this as a "What it means" tab when an entry exists.
 *
 * GENERATED by scripts/gen_what_it_means.mjs — edit the source data / re-run,
 * don't hand-edit the record below.
 */

export interface VariableMeaning {
  /** The symbol exactly as it reads in the formula, e.g. "m₁", "r", "P(A|B)". */
  symbol: string
  /** Plain-English name, e.g. "mass of the first body". */
  name: string
  /** What it actually represents, in one sentence. */
  meaning: string
  /** Optional unit, e.g. "kg", "m/s". Omit for dimensionless quantities. */
  unit?: string
}

export interface WhatItMeans {
  /** 1–2 sentences: what the equation is really saying, in plain English. */
  plainEnglish: string
  /** Each symbol in the formula, decoded. At least one. */
  variables: VariableMeaning[]
  /** What the result / left-hand side represents and how to read it. */
  result: string
  /** The "so what" — the intuition, or why the relationship matters. */
  interpretation: string
}

export const whatItMeans: Record<number, WhatItMeans> = {
`

const footer = `}

/** The "what does it mean" decoding for an equation, or null if none is curated. */
export function getWhatItMeans(equationId: number): WhatItMeans | null {
  return whatItMeans[equationId] ?? null
}
`

const body = sorted.map(renderEntry).join("\n")
writeFileSync(outPath, header + body + "\n" + footer, "utf8")
console.log(`wrote ${sorted.length} entries to ${outPath.pathname} (ids ${sorted[0]?.id}..${sorted[sorted.length - 1]?.id})`)
